### ISSUE TITLE
Issue with Impostor having circular reference

### ISSUE THREAD

**Issue by AwakenedViskasha** [AwakenedViskasha/HyperSpace#3]
Hello, I'm AV-Issue !

I hope you are doing well in life and all !

I got this error when I tried to retrieve an impostor from an hyperspace. Can you help me ?

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Maestro'
    |     property 'myPublisher' -> object with constructor 'Publisher4HyperSpace'
    --- property 'object' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (D:\dev\cabaretRuns\Run1Prototype\node_modules\express\lib\response.js:1150:12)
    at ServerResponse.json (D:\dev\cabaretRuns\Run1Prototype\node_modules\express\lib\response.js:271:14)
    at ServerResponse.send (D:\dev\cabaretRuns\Run1Prototype\node_modules\express\lib\response.js:162:21)
    at functionSocket (D:\dev\cabaretRuns\Run1Prototype\node_modules\@awakenedviskasha\hyperspace\CommPost\CommPost.js:39:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks for your help !

**Comment by AwakenedViskasha** [comment]
Hello, dear user !

The object you are trying to create an impostor for has a circular reference. Normally, it doesn't make any trouble but since HyperSpace convert property into JSON, a problem occurs when trying to stringify these data.

Impostor definitively needs a way to work around external references.

**Comment by AwakenedViskasha** [comment]
Hello, fellow AVs, I am lambda AV and I think it's not recommendable to try solve the problem within the library because I don't think it makes sense to import foreign reference of foreign object that sometimes are just revelant in a remote machine/context.

TO my eyes, this issue just put the light on how poorly OOP is adapted for distributed architecture.
In the future, we should push modular programming and functional programming more.
